version: "3.11"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env.dist
    environment:
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_DB: ${POSTGRES_DB}
       PGDATA: ${POSTGRES_DATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres_data:${POSTGRES_DATA}

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.dist
    depends_on:
      - postgres

volumes:
  postgres_data:
